
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: multimodal-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: multimodal_search_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - multimodal-dev

  redis:
    image: redis:7-alpine
    container_name: multimodal-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - multimodal-dev

  backend:
    build:
      context: ../..
      dockerfile: infra/dev/docker/Dockerfile.backend
    container_name: multimodal-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
      - ../../storage:/app/storage
    env_file:
      - ./env/.env.dev
    environment:
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - multimodal-dev

  frontend:
    build:
      context: ../..
      dockerfile: infra/dev/docker/Dockerfile.frontend
    container_name: multimodal-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    networks:
      - multimodal-dev

  nginx:
    image: nginx:alpine
    container_name: multimodal-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
      - ../../storage/uploads:/var/www/uploads:ro
    depends_on:
      - backend
      - frontend
    networks:
      - multimodal-dev

networks:
  multimodal-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  redis_data_dev:
